name: r
channels:
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
  - daler
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/bioconda
  - dnachun
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - conda-forge
  - bioconda
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - _r-xgboost-mutex=2.0
  - anndata=0.10.2
  - anyio=3.7.1
  - argcomplete=3.1.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.8.0
  - array-api-compat=1.4
  - asttokens=2.2.1
  - attrs=23.1.0
  - aws-c-auth=0.7.0
  - aws-c-cal=0.6.0
  - aws-c-common=0.8.23
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.28
  - aws-c-mqtt=0.8.14
  - aws-c-s3=0.3.13
  - aws-c-sdkutils=0.1.11
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.3
  - aws-sdk-cpp=1.10.57
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - binutils_impl_linux-64=2.40
  - bioconductor-annotate=1.78.0
  - bioconductor-annotationdbi=1.62.2
  - bioconductor-aucell=1.22.0
  - bioconductor-basilisk=1.12.1
  - bioconductor-basilisk.utils=1.12.1
  - bioconductor-bcellviper=1.36.0
  - bioconductor-beachmat=2.16.0
  - bioconductor-biobase=2.60.0
  - bioconductor-biocgenerics=0.46.0
  - bioconductor-biocio=1.10.0
  - bioconductor-biocneighbors=1.18.0
  - bioconductor-biocparallel=1.34.2
  - bioconductor-biocsingular=1.16.0
  - bioconductor-biocviews=1.68.1
  - bioconductor-biostrings=2.68.1
  - bioconductor-bluster=1.10.0
  - bioconductor-clusterprofiler=4.8.1
  - bioconductor-complexheatmap=2.16.0
  - bioconductor-data-packages=20230718
  - bioconductor-decoupler=2.6.0
  - bioconductor-delayedarray=0.26.6
  - bioconductor-delayedmatrixstats=1.22.1
  - bioconductor-densvis=1.10.2
  - bioconductor-deseq2=1.40.2
  - bioconductor-dir.expiry=1.8.0
  - bioconductor-dorothea=1.12.0
  - bioconductor-dose=3.26.1
  - bioconductor-dyndoc=1.78.0
  - bioconductor-edger=3.42.4
  - bioconductor-enrichplot=1.20.0
  - bioconductor-fgsea=1.26.0
  - bioconductor-genefilter=1.82.1
  - bioconductor-genomeinfodb=1.36.1
  - bioconductor-genomeinfodbdata=1.2.10
  - bioconductor-genomicalignments=1.36.0
  - bioconductor-genomicranges=1.52.0
  - bioconductor-ggtree=3.8.0
  - bioconductor-go.db=3.17.0
  - bioconductor-gosemsim=2.26.0
  - bioconductor-graph=1.78.0
  - bioconductor-graphite=1.46.0
  - bioconductor-gseabase=1.62.0
  - bioconductor-hdo.db=0.99.1
  - bioconductor-infercnv=1.16.0
  - bioconductor-iranges=2.34.1
  - bioconductor-kegggraph=1.60.0
  - bioconductor-keggrest=1.40.0
  - bioconductor-limma=3.56.2
  - bioconductor-matrixgenerics=1.12.2
  - bioconductor-metapod=1.8.0
  - bioconductor-mfuzz=2.60.0
  - bioconductor-omnipathr=3.10.1
  - bioconductor-org.hs.eg.db=3.17.0
  - bioconductor-pathview=1.40.0
  - bioconductor-progeny=1.22.0
  - bioconductor-qvalue=2.32.0
  - bioconductor-rbgl=1.76.0
  - bioconductor-rcistarget=1.20.0
  - bioconductor-reactome.db=1.84.0
  - bioconductor-reactomepa=1.44.0
  - bioconductor-rgraphviz=2.44.0
  - bioconductor-rhtslib=2.2.0
  - bioconductor-rsamtools=2.16.0
  - bioconductor-rtracklayer=1.60.0
  - bioconductor-s4arrays=1.0.4
  - bioconductor-s4vectors=0.38.1
  - bioconductor-scaledmatrix=1.8.1
  - bioconductor-scater=1.28.0
  - bioconductor-scdblfinder=1.14.0
  - bioconductor-scran=1.28.1
  - bioconductor-scuttle=1.10.1
  - bioconductor-singlecellexperiment=1.22.0
  - bioconductor-sparsematrixstats=1.12.2
  - bioconductor-summarizedexperiment=1.30.2
  - bioconductor-sva=3.48.0
  - bioconductor-tkwidgets=1.78.0
  - bioconductor-treeio=1.24.1
  - bioconductor-widgettools=1.78.0
  - bioconductor-xvector=0.40.0
  - bioconductor-zlibbioc=1.46.0
  - bleach=6.0.0
  - blosc=1.21.4
  - boltons=23.0.0
  - brotli=1.0.9
  - brotli-python=1.0.9
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - celltypist=1.6.1
  - certifi=2024.2.2
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.3
  - conda=23.5.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.8.0
  - cryptography=41.0.2
  - curl=8.4.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.2
  - executing=1.2.0
  - expat=2.5.0
  - flit-core=3.9.0
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=13.1.0
  - gettext=0.21.1
  - gflags=2.2.2
  - gfortran_impl_linux-64=13.1.0
  - glib=2.78.1
  - glib-tools=2.78.1
  - glog=0.6.0
  - glpk=5.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=13.1.0
  - harfbuzz=8.3.0
  - hdf4=4.2.15
  - hdf5=1.14.1
  - htslib=1.17
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.0
  - ipykernel=6.24.0
  - ipython=8.14.0
  - ipython_genutils=0.2.0
  - jags=4.3.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.3.2
  - jq=1.5
  - jsonpatch=1.32
  - jsonpointer=2.0
  - jsonschema=4.18.2
  - jsonschema-specifications=2023.6.1
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - jupyter_events=0.6.3
  - jupyter_server=2.7.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.21.2
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leidenalg=0.10.1
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.0.6
  - libarchive=3.6.2
  - libarrow=12.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.4.0
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-devel_linux-64=13.1.0
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgit2=1.6.4
  - libglib=2.78.1
  - libglu=9.0.0
  - libgomp=13.1.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.56.2
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libleidenalg=0.11.1
  - libllvm14=14.0.6
  - libmamba=1.4.9
  - libmambapy=1.4.9
  - libnetcdf=4.9.2
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libnuma=2.0.18
  - libopenblas=0.3.23
  - libpng=1.6.43
  - libprotobuf=4.23.3
  - libsanitizer=13.1.0
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=13.1.0
  - libstdcxx-ng=13.1.0
  - libthrift=0.18.1
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxgboost=1.7.6
  - libxml2=2.11.6
  - libzip=1.10.1
  - libzlib=1.2.13
  - loompy=2.0.16
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.3
  - mamba=1.4.9
  - markupsafe=2.1.3
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=3.0.0
  - mpfr=4.2.0
  - multipledispatch=0.6.0
  - munkres=1.0.7
  - natsort=8.4.0
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.6.0
  - nbconvert-core=7.6.0
  - nbconvert-pandoc=7.6.0
  - nbformat=5.9.1
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nlopt=2.7.1
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - numba=0.57.1
  - numpy=1.24.4
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=3.2.1
  - orc=1.9.0
  - overrides=7.3.1
  - packaging=23.1
  - pandas-flavor=0.6.0
  - pandas_flavor=0.6.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - pango=1.50.14
  - parso=0.8.3
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.1.2
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.8.1
  - pluggy=1.2.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pygments=2.15.1
  - pyjanitor=0.27.0
  - pynndescent=0.5.10
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.4
  - python-annoy=1.17.2
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.17.1
  - python-igraph=0.11.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pyyaml=6.0
  - pyzmq=25.1.0
  - r-abind=1.4_5
  - r-afex=1.3_0
  - r-ape=5.7_1
  - r-aplot=0.2.0
  - r-argparse=2.2.2
  - r-arrow=12.0.1
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.3.2
  - r-base64enc=0.1_3
  - r-bayesfactor=0.9.12_4.4
  - r-bayestestr=0.13.1
  - r-beeswarm=0.4.0
  - r-bh=1.81.0_1
  - r-bibtex=0.5.1
  - r-biocmanager=1.30.21
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.4
  - r-boot=1.3_28.1
  - r-brew=1.0_8
  - r-brio=1.1.3
  - r-broom=1.0.5
  - r-bslib=0.5.0
  - r-bwstest=0.2.2
  - r-cachem=1.0.8
  - r-cairo=1.6_1
  - r-callr=3.7.3
  - r-car=3.1_2
  - r-cardata=3.0_5
  - r-caret=6.0_94
  - r-catools=1.18.2
  - r-cellchat=1.5.0
  - r-cellranger=1.1.0
  - r-checkmate=2.3.0
  - r-circlize=0.4.15
  - r-class=7.3_22
  - r-cli=3.6.1
  - r-clipr=0.8.0
  - r-clock=0.7.0
  - r-clue=0.3_64
  - r-cluster=2.1.4
  - r-coda=0.19_4
  - r-codetools=0.2_19
  - r-coin=1.4_3
  - r-colorspace=2.1_0
  - r-commonmark=1.9.0
  - r-conflicted=1.2.0
  - r-conquer=1.3.3
  - r-contfrac=1.1_12
  - r-correlation=0.8.4
  - r-corrplot=0.92
  - r-cowplot=1.1.1
  - r-cpp11=0.4.4
  - r-crayon=1.5.2
  - r-credentials=1.3.2
  - r-crosstalk=1.2.0
  - r-crul=1.4.0
  - r-curl=5.0.1
  - r-data.table=1.14.8
  - r-datawizard=0.9.0
  - r-dbi=1.1.3
  - r-dbplyr=2.3.3
  - r-deldir=1.0_9
  - r-desc=1.4.2
  - r-desolve=1.38
  - r-devtools=2.4.5
  - r-diagram=1.6.5
  - r-dichromat=2.0_0.1
  - r-diffobj=0.3.5
  - r-digest=0.6.33
  - r-doparallel=1.0.17
  - r-downlit=0.4.3
  - r-downloader=0.4
  - r-dplyr=1.1.2
  - r-dqrng=0.3.1
  - r-dtplyr=1.3.1
  - r-e1071=1.7_13
  - r-effectsize=0.8.6
  - r-ellipsis=0.3.2
  - r-elliptic=1.4_0
  - r-essentials=4.3
  - r-evaluate=0.21
  - r-expm=0.999_7
  - r-fansi=1.0.4
  - r-farver=2.1.1
  - r-fastcluster=1.2.3
  - r-fastmap=1.1.1
  - r-fastmatch=1.1_4
  - r-filelock=1.0.3
  - r-findpython=1.0.8
  - r-fitdistrplus=1.1_11
  - r-fnn=1.1.3.2
  - r-fontawesome=0.5.1
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_84
  - r-formatr=1.14
  - r-fs=1.6.2
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.33.0
  - r-future.apply=1.11.0
  - r-gameofthrones=1.0.2
  - r-gargle=1.5.1
  - r-gbrd=0.4_11
  - r-generics=0.1.3
  - r-gert=1.9.2
  - r-getoptlong=1.0.5
  - r-ggalluvial=0.12.5
  - r-ggbeeswarm=0.7.2
  - r-ggcorrplot=0.1.4.1
  - r-ggforce=0.4.1
  - r-ggfun=0.1.2
  - r-ggnetwork=0.5.12
  - r-ggnewscale=0.4.9
  - r-ggplot2=3.4.2
  - r-ggplotify=0.1.2
  - r-ggpubr=0.6.0
  - r-ggraph=2.1.0
  - r-ggrastr=1.0.2
  - r-ggrepel=0.9.3
  - r-ggridges=0.5.4
  - r-ggsci=3.0.0
  - r-ggside=0.2.2
  - r-ggsignif=0.6.4
  - r-ggstatsplot=0.12.0
  - r-ggthemes=4.2.4
  - r-gh=1.4.0
  - r-gistr=0.9.0
  - r-gitcreds=0.1.2
  - r-glmnet=4.1_7
  - r-globaloptions=0.1.2
  - r-globals=0.16.2
  - r-glue=1.6.2
  - r-gmp=0.7_2
  - r-goftest=1.2_3
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gower=1.0.1
  - r-gplots=3.1.3
  - r-graphlayouts=1.0.0
  - r-gridbase=0.4_7
  - r-gridextra=2.3
  - r-gridgraphics=0.5_1
  - r-gson=0.1.0
  - r-gtable=0.3.3
  - r-gtools=3.9.4
  - r-hardhat=1.3.0
  - r-harrypotter=2.1.1
  - r-haven=2.5.3
  - r-here=1.0.1
  - r-hexbin=1.28.3
  - r-hiclimr=2.2.1
  - r-hiddenmarkov=1.8_13
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.5
  - r-htmlwidgets=1.6.2
  - r-httpcode=0.3.0
  - r-httpuv=1.6.11
  - r-httr=1.4.6
  - r-httr2=0.2.3
  - r-hypergeo=1.2_13
  - r-ica=1.0_3
  - r-ids=1.0.1
  - r-igraph=1.5.0.1
  - r-ini=0.3.1
  - r-insight=0.19.5
  - r-ipred=0.9_14
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-irlba=2.3.5.1
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-janitor=2.2.0
  - r-jcolors=0.0.4
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.7
  - r-kernlab=0.9_32
  - r-kernsmooth=2.23_22
  - r-knitr=1.43
  - r-ksamples=1.2_9
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-later=1.3.1
  - r-lattice=0.21_8
  - r-lava=1.7.2.1
  - r-lazyeval=0.2.2
  - r-leiden=0.4.3
  - r-libcoin=1.0_10
  - r-lifecycle=1.0.3
  - r-listenv=0.9.0
  - r-lme4=1.1_34
  - r-lmertest=3.1_3
  - r-lmtest=0.9_40
  - r-lobstr=1.1.2
  - r-locfit=1.5_9.8
  - r-logger=0.3.0
  - r-lsei=1.3_0
  - r-lubridate=1.9.2
  - r-magrittr=2.0.3
  - r-manipulatewidget=0.11.1
  - r-mapproj=1.2.11
  - r-maps=3.4.1
  - r-maptools=1.1_7
  - r-mass=7.3_60
  - r-matrix=1.6_0
  - r-matrixmodels=0.5_2
  - r-matrixstats=1.0.0
  - r-mc2d=0.2.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_0
  - r-mime=0.12
  - r-miniui=0.1.1.1
  - r-minqa=1.2.5
  - r-mixtools=2.0.0
  - r-mnormt=2.1.1
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-modeltools=0.2_23
  - r-multcomp=1.4_25
  - r-multcompview=0.1_9
  - r-munsell=0.5.0
  - r-mvtnorm=1.2_3
  - r-ncdf4=1.21
  - r-network=1.18.1
  - r-nlme=3.1_162
  - r-nloptr=2.0.3
  - r-nmf=0.24.0
  - r-nnet=7.3_19
  - r-npsurv=0.5_0
  - r-numderiv=2016.8_1.1
  - r-oompabase=3.2.9
  - r-openssl=2.0.6
  - r-openxlsx=4.2.5.2
  - r-paletteer=1.5.0
  - r-palr=0.3.0
  - r-pals=1.8
  - r-paralleldist=0.2.6
  - r-parallelly=1.36.0
  - r-parameters=0.21.2
  - r-patchwork=1.1.3
  - r-pbapply=1.7_2
  - r-pbdzmq=0.3_9
  - r-pbkrtest=0.5.2
  - r-performance=0.10.5
  - r-pheatmap=1.0.12
  - r-phyclust=0.1_34
  - r-pillar=1.9.0
  - r-pkgbuild=1.4.2
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.0.7
  - r-pkgload=1.3.2.1
  - r-pkgmaker=0.32.10
  - r-plogr=0.2.0
  - r-plotly=4.10.2
  - r-plyr=1.8.8
  - r-pma=1.2_3
  - r-pmcmrplus=1.9.7
  - r-png=0.1_8
  - r-polyclip=1.10_4
  - r-polynom=1.4_1
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-prismatic=1.1.1
  - r-proc=1.18.4
  - r-processx=3.8.2
  - r-prodlim=2023.03.31
  - r-profvis=0.3.8
  - r-progress=1.2.2
  - r-progressr=0.13.0
  - r-promises=1.2.0.1
  - r-proxy=0.4_27
  - r-pryr=0.1.6
  - r-ps=1.7.5
  - r-psych=2.4.3
  - r-purrr=1.0.1
  - r-quantmod=0.4.23
  - r-quantreg=5.95
  - r-r.methodss3=1.8.2
  - r-r.oo=1.26.0
  - r-r.utils=2.12.3
  - r-r6=2.5.1
  - r-ragg=1.3.0
  - r-randomforest=4.7_1.1
  - r-rann=2.6.1
  - r-rappdirs=0.3.3
  - r-rbibutils=2.2.16
  - r-rbokeh=0.5.2
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.11
  - r-rcppannoy=0.0.21
  - r-rcpparmadillo=0.12.4.1.0
  - r-rcppeigen=0.3.3.9.3
  - r-rcpphnsw=0.4.1
  - r-rcppml=0.3.7
  - r-rcppparallel=5.1.6
  - r-rcppprogress=0.4.2
  - r-rcpptoml=0.2.2
  - r-rcurl=1.98_1.12
  - r-rdpack=2.6
  - r-readr=2.1.4
  - r-readxl=1.4.3
  - r-recipes=1.0.6
  - r-recommended=4.3
  - r-registry=0.5_1
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-remotes=2.4.2
  - r-repr=1.1.6
  - r-reprex=2.0.2
  - r-reshape=0.8.9
  - r-reshape2=1.4.4
  - r-restfulr=0.0.15
  - r-reticulate=1.32.0
  - r-rgl=1.2.1
  - r-rio=0.5.29
  - r-rjags=4_14
  - r-rjson=0.2.21
  - r-rlang=1.1.1
  - r-rle=0.9.2
  - r-rmarkdown=2.23
  - r-rmpfr=0.9_3
  - r-rngtools=1.5.2
  - r-rocr=1.0_11
  - r-roxygen2=7.2.3
  - r-rpart=4.1.19
  - r-rprojroot=2.0.3
  - r-rspectra=0.16_1
  - r-rsqlite=2.3.1
  - r-rstatix=0.7.2
  - r-rstudioapi=0.15.0
  - r-rsvd=1.0.5
  - r-rtsne=0.16
  - r-runit=0.4.32
  - r-rversions=2.1.2
  - r-rvest=1.0.3
  - r-sandwich=3.0_2
  - r-sass=0.4.6
  - r-scales=1.2.1
  - r-scattermore=1.2
  - r-scatterpie=0.2.1
  - r-scico=1.5.0
  - r-sctransform=0.4.0
  - r-segmented=2.0_4
  - r-selectr=0.4_2
  - r-sessioninfo=1.2.2
  - r-seurat=4.4.0
  - r-seuratobject=4.1.4
  - r-shadowtext=0.1.2
  - r-shape=1.4.6
  - r-shiny=1.7.4.1
  - r-shinyjs=2.1.0
  - r-sitmo=2.0.2
  - r-sna=2.7_1
  - r-snakecase=0.11.1
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-sp=1.6_1
  - r-sparsem=1.81
  - r-spatial=7.3_16
  - r-spatstat.data=3.0_1
  - r-spatstat.explore=3.2_3
  - r-spatstat.geom=3.2_5
  - r-spatstat.random=3.1_6
  - r-spatstat.sparse=3.0_2
  - r-spatstat.utils=3.0_3
  - r-squarem=2021.1
  - r-statmod=1.5.0
  - r-statnet.common=4.9.0
  - r-statsexpressions=1.5.1
  - r-stringi=1.8.3
  - r-stringr=1.5.0
  - r-suppdists=1.1_9.7
  - r-survival=3.5_5
  - r-svglite=2.1.1
  - r-sys=3.4.2
  - r-systemfonts=1.0.4
  - r-tensor=1.5
  - r-tester=0.1.7
  - r-testthat=3.1.10
  - r-textshaping=0.3.7
  - r-th.data=1.1_2
  - r-tibble=3.2.1
  - r-tidygraph=1.2.3
  - r-tidyr=1.3.0
  - r-tidyselect=1.2.0
  - r-tidytree=0.4.5
  - r-tidyverse=2.0.0
  - r-timechange=0.2.0
  - r-timedate=4022.108
  - r-tinytex=0.45
  - r-tmvnsim=1.0_2
  - r-triebeard=0.4.1
  - r-ttr=0.24.3
  - r-tweenr=2.0.2
  - r-tzdb=0.4.0
  - r-urlchecker=1.0.1
  - r-urltools=1.7.3
  - r-usethis=2.2.2
  - r-utf8=1.2.3
  - r-uuid=1.1_0
  - r-uwot=0.1.16
  - r-vctrs=0.6.3
  - r-vipor=0.4.5
  - r-viridis=0.6.4
  - r-viridislite=0.4.2
  - r-vroom=1.6.3
  - r-waldo=0.5.1
  - r-webshot=0.5.5
  - r-whisker=0.4.1
  - r-withr=2.5.0
  - r-wrs2=1.1_4
  - r-xfun=0.39
  - r-xgboost=1.7.6
  - r-xml=3.99_0.14
  - r-xml2=1.3.5
  - r-xopen=1.0.0
  - r-xtable=1.8_4
  - r-xts=0.13.1
  - r-yaml=2.3.7
  - r-yulab.utils=0.0.9
  - r-zeallot=0.1.0
  - r-zip=2.3.0
  - r-zoo=1.8_12
  - rdma-core=28.9
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.29.1
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.8.10
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - s2n=1.3.46
  - scanpy=1.9.5
  - scikit-learn=1.3.2
  - scipy=1.11.3
  - seaborn=0.13.0
  - seaborn-base=0.13.0
  - sed=4.8
  - send2trash=1.8.2
  - seqtk=1.3
  - session-info=1.0.0
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sratoolkit=2.5.7
  - stack_data=0.6.2
  - star=2.7.11a
  - statsmodels=0.14.0
  - sysroot_linux-64=2.12
  - tbb=2021.10.0
  - terminado=0.17.1
  - texttable=1.7.0
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomlkit=0.12.1
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing=3.10.0.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2023c
  - ucx=1.14.1
  - urllib3=2.0.3
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - wheel=0.40.0
  - xarray=2024.3.0
  - xlrd=2.0.1
  - xmltodict=0.13.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - yq=3.2.3
  - zeromq=4.3.4
  - zipp=3.16.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - annoy==1.17.3
      - contourpy==1.1.0
      - cycler==0.11.0
      - cython==3.0.0
      - fbpca==1.0
      - fonttools==4.42.0
      - future==0.18.3
      - geosketch==1.2
      - h5py==3.10.0
      - igraph==0.10.8
      - imageio==2.31.1
      - intervaltree==2.1.0
      - kiwisolver==1.4.4
      - lazy-loader==0.3
      - llvmlite==0.40.1
      - matplotlib==3.7.2
      - networkx==3.1
      - pandas==2.0.3
      - pybktree==1.1
      - pyparsing==3.0.9
      - pysam==0.22.0
      - pytz==2023.3
      - pywavelets==1.4.1
      - regex==2023.10.3
      - scanoramact==1.2.0
      - scikit-image==0.21.0
      - scrublet==0.2.3
      - sortedcontainers==2.4.0
      - stdlib-list==0.9.0
      - tifffile==2023.7.18
      - umap-learn==0.5.3
      - umi-tools==1.1.4
